import { SiteConfig } from "./site-config";

/**
 * Change this single value to switch the active site.
 * Must match a key in the `sites` record below.
 */
export const ACTIVE_SITE = "alaska-express";

export const sites: Record<string, SiteConfig> = {
  "alaska-express": {
    slug: "alaska-express",
    name: "Alaska Express",
    logoFirst: "ALASKA",
    logoSecond: "EXPRESS",
    city: "Anchorage",
    state: "Alaska",
    stateAbbr: "AK",
    tagline: "Alaska's #1 News Source",
  },
  "nevada-express": {
    slug: "nevada-express",
    name: "Nevada Express",
    logoFirst: "NEVADA",
    logoSecond: "EXPRESS",
    city: "Las Vegas",
    state: "Nevada",
    stateAbbr: "NV",
    tagline: "Nevada's #1 News Source",
  },
  "texas-tribune": {
    slug: "texas-tribune",
    name: "Texas Tribune",
    logoFirst: "TEXAS",
    logoSecond: "TRIBUNE",
    city: "Austin",
    state: "Texas",
    stateAbbr: "TX",
    tagline: "Texas' #1 News Source",
  },
  "florida-sun": {
    slug: "florida-sun",
    name: "Florida Sun",
    logoFirst: "FLORIDA",
    logoSecond: "SUN",
    city: "Miami",
    state: "Florida",
    stateAbbr: "FL",
    tagline: "Florida's #1 News Source",
  },
  "california-herald": {
    slug: "california-herald",
    name: "California Herald",
    logoFirst: "CALIFORNIA",
    logoSecond: "HERALD",
    city: "Los Angeles",
    state: "California",
    stateAbbr: "CA",
    tagline: "California's #1 News Source",
  },
  "new-york-post-express": {
    slug: "new-york-post-express",
    name: "New York Post Express",
    logoFirst: "NEW YORK",
    logoSecond: "POST EXPRESS",
    city: "New York City",
    state: "New York",
    stateAbbr: "NY",
    tagline: "New York's #1 News Source",
  },
  "ohio-dispatch": {
    slug: "ohio-dispatch",
    name: "Ohio Dispatch",
    logoFirst: "OHIO",
    logoSecond: "DISPATCH",
    city: "Columbus",
    state: "Ohio",
    stateAbbr: "OH",
    tagline: "Ohio's #1 News Source",
  },
  "michigan-record": {
    slug: "michigan-record",
    name: "Michigan Record",
    logoFirst: "MICHIGAN",
    logoSecond: "RECORD",
    city: "Detroit",
    state: "Michigan",
    stateAbbr: "MI",
    tagline: "Michigan's #1 News Source",
  },
  "georgia-gazette": {
    slug: "georgia-gazette",
    name: "Georgia Gazette",
    logoFirst: "GEORGIA",
    logoSecond: "GAZETTE",
    city: "Atlanta",
    state: "Georgia",
    stateAbbr: "GA",
    tagline: "Georgia's #1 News Source",
  },
  "arizona-star": {
    slug: "arizona-star",
    name: "Arizona Star",
    logoFirst: "ARIZONA",
    logoSecond: "STAR",
    city: "Phoenix",
    state: "Arizona",
    stateAbbr: "AZ",
    tagline: "Arizona's #1 News Source",
  },
  "colorado-times": {
    slug: "colorado-times",
    name: "Colorado Times",
    logoFirst: "COLORADO",
    logoSecond: "TIMES",
    city: "Denver",
    state: "Colorado",
    stateAbbr: "CO",
    tagline: "Colorado's #1 News Source",
  },
  "illinois-herald": {
    slug: "illinois-herald",
    name: "Illinois Herald",
    logoFirst: "ILLINOIS",
    logoSecond: "HERALD",
    city: "Chicago",
    state: "Illinois",
    stateAbbr: "IL",
    tagline: "Illinois' #1 News Source",
  },
  "pennsylvania-press": {
    slug: "pennsylvania-press",
    name: "Pennsylvania Press",
    logoFirst: "PENNSYLVANIA",
    logoSecond: "PRESS",
    city: "Philadelphia",
    state: "Pennsylvania",
    stateAbbr: "PA",
    tagline: "Pennsylvania's #1 News Source",
  },
  "north-carolina-record": {
    slug: "north-carolina-record",
    name: "North Carolina Record",
    logoFirst: "NORTH CAROLINA",
    logoSecond: "RECORD",
    city: "Charlotte",
    state: "North Carolina",
    stateAbbr: "NC",
    tagline: "North Carolina's #1 News Source",
  },
  "virginia-post": {
    slug: "virginia-post",
    name: "Virginia Post",
    logoFirst: "VIRGINIA",
    logoSecond: "POST",
    city: "Richmond",
    state: "Virginia",
    stateAbbr: "VA",
    tagline: "Virginia's #1 News Source",
  },
  "washington-express": {
    slug: "washington-express",
    name: "Washington Express",
    logoFirst: "WASHINGTON",
    logoSecond: "EXPRESS",
    city: "Seattle",
    state: "Washington",
    stateAbbr: "WA",
    tagline: "Washington's #1 News Source",
  },
  "oregon-herald": {
    slug: "oregon-herald",
    name: "Oregon Herald",
    logoFirst: "OREGON",
    logoSecond: "HERALD",
    city: "Portland",
    state: "Oregon",
    stateAbbr: "OR",
    tagline: "Oregon's #1 News Source",
  },
  "massachusetts-globe": {
    slug: "massachusetts-globe",
    name: "Massachusetts Globe",
    logoFirst: "MASSACHUSETTS",
    logoSecond: "GLOBE",
    city: "Boston",
    state: "Massachusetts",
    stateAbbr: "MA",
    tagline: "Massachusetts' #1 News Source",
  },
  "tennessee-times": {
    slug: "tennessee-times",
    name: "Tennessee Times",
    logoFirst: "TENNESSEE",
    logoSecond: "TIMES",
    city: "Nashville",
    state: "Tennessee",
    stateAbbr: "TN",
    tagline: "Tennessee's #1 News Source",
  },
  "indiana-star": {
    slug: "indiana-star",
    name: "Indiana Star",
    logoFirst: "INDIANA",
    logoSecond: "STAR",
    city: "Indianapolis",
    state: "Indiana",
    stateAbbr: "IN",
    tagline: "Indiana's #1 News Source",
  },
  "maryland-tribune": {
    slug: "maryland-tribune",
    name: "Maryland Tribune",
    logoFirst: "MARYLAND",
    logoSecond: "TRIBUNE",
    city: "Baltimore",
    state: "Maryland",
    stateAbbr: "MD",
    tagline: "Maryland's #1 News Source",
  },
  "missouri-dispatch": {
    slug: "missouri-dispatch",
    name: "Missouri Dispatch",
    logoFirst: "MISSOURI",
    logoSecond: "DISPATCH",
    city: "Kansas City",
    state: "Missouri",
    stateAbbr: "MO",
    tagline: "Missouri's #1 News Source",
  },
  "wisconsin-record": {
    slug: "wisconsin-record",
    name: "Wisconsin Record",
    logoFirst: "WISCONSIN",
    logoSecond: "RECORD",
    city: "Milwaukee",
    state: "Wisconsin",
    stateAbbr: "WI",
    tagline: "Wisconsin's #1 News Source",
  },
  "minnesota-herald": {
    slug: "minnesota-herald",
    name: "Minnesota Herald",
    logoFirst: "MINNESOTA",
    logoSecond: "HERALD",
    city: "Minneapolis",
    state: "Minnesota",
    stateAbbr: "MN",
    tagline: "Minnesota's #1 News Source",
  },
  "south-carolina-sun": {
    slug: "south-carolina-sun",
    name: "South Carolina Sun",
    logoFirst: "SOUTH CAROLINA",
    logoSecond: "SUN",
    city: "Charleston",
    state: "South Carolina",
    stateAbbr: "SC",
    tagline: "South Carolina's #1 News Source",
  },
  "alabama-times": {
    slug: "alabama-times",
    name: "Alabama Times",
    logoFirst: "ALABAMA",
    logoSecond: "TIMES",
    city: "Birmingham",
    state: "Alabama",
    stateAbbr: "AL",
    tagline: "Alabama's #1 News Source",
  },
  "louisiana-press": {
    slug: "louisiana-press",
    name: "Louisiana Press",
    logoFirst: "LOUISIANA",
    logoSecond: "PRESS",
    city: "New Orleans",
    state: "Louisiana",
    stateAbbr: "LA",
    tagline: "Louisiana's #1 News Source",
  },
  "kentucky-herald": {
    slug: "kentucky-herald",
    name: "Kentucky Herald",
    logoFirst: "KENTUCKY",
    logoSecond: "HERALD",
    city: "Louisville",
    state: "Kentucky",
    stateAbbr: "KY",
    tagline: "Kentucky's #1 News Source",
  },
  "oklahoma-gazette": {
    slug: "oklahoma-gazette",
    name: "Oklahoma Gazette",
    logoFirst: "OKLAHOMA",
    logoSecond: "GAZETTE",
    city: "Oklahoma City",
    state: "Oklahoma",
    stateAbbr: "OK",
    tagline: "Oklahoma's #1 News Source",
  },
  "connecticut-post": {
    slug: "connecticut-post",
    name: "Connecticut Post",
    logoFirst: "CONNECTICUT",
    logoSecond: "POST",
    city: "Hartford",
    state: "Connecticut",
    stateAbbr: "CT",
    tagline: "Connecticut's #1 News Source",
  },
  "iowa-register": {
    slug: "iowa-register",
    name: "Iowa Register",
    logoFirst: "IOWA",
    logoSecond: "REGISTER",
    city: "Des Moines",
    state: "Iowa",
    stateAbbr: "IA",
    tagline: "Iowa's #1 News Source",
  },
  "utah-tribune": {
    slug: "utah-tribune",
    name: "Utah Tribune",
    logoFirst: "UTAH",
    logoSecond: "TRIBUNE",
    city: "Salt Lake City",
    state: "Utah",
    stateAbbr: "UT",
    tagline: "Utah's #1 News Source",
  },
  "arkansas-record": {
    slug: "arkansas-record",
    name: "Arkansas Record",
    logoFirst: "ARKANSAS",
    logoSecond: "RECORD",
    city: "Little Rock",
    state: "Arkansas",
    stateAbbr: "AR",
    tagline: "Arkansas' #1 News Source",
  },
  "kansas-star": {
    slug: "kansas-star",
    name: "Kansas Star",
    logoFirst: "KANSAS",
    logoSecond: "STAR",
    city: "Wichita",
    state: "Kansas",
    stateAbbr: "KS",
    tagline: "Kansas' #1 News Source",
  },
  "mississippi-sun": {
    slug: "mississippi-sun",
    name: "Mississippi Sun",
    logoFirst: "MISSISSIPPI",
    logoSecond: "SUN",
    city: "Jackson",
    state: "Mississippi",
    stateAbbr: "MS",
    tagline: "Mississippi's #1 News Source",
  },
  "nebraska-herald": {
    slug: "nebraska-herald",
    name: "Nebraska Herald",
    logoFirst: "NEBRASKA",
    logoSecond: "HERALD",
    city: "Omaha",
    state: "Nebraska",
    stateAbbr: "NE",
    tagline: "Nebraska's #1 News Source",
  },
  "new-mexico-express": {
    slug: "new-mexico-express",
    name: "New Mexico Express",
    logoFirst: "NEW MEXICO",
    logoSecond: "EXPRESS",
    city: "Albuquerque",
    state: "New Mexico",
    stateAbbr: "NM",
    tagline: "New Mexico's #1 News Source",
  },
  "idaho-press": {
    slug: "idaho-press",
    name: "Idaho Press",
    logoFirst: "IDAHO",
    logoSecond: "PRESS",
    city: "Boise",
    state: "Idaho",
    stateAbbr: "ID",
    tagline: "Idaho's #1 News Source",
  },
  "hawaii-times": {
    slug: "hawaii-times",
    name: "Hawaii Times",
    logoFirst: "HAWAII",
    logoSecond: "TIMES",
    city: "Honolulu",
    state: "Hawaii",
    stateAbbr: "HI",
    tagline: "Hawaii's #1 News Source",
  },
  "west-virginia-gazette": {
    slug: "west-virginia-gazette",
    name: "West Virginia Gazette",
    logoFirst: "WEST VIRGINIA",
    logoSecond: "GAZETTE",
    city: "Charleston",
    state: "West Virginia",
    stateAbbr: "WV",
    tagline: "West Virginia's #1 News Source",
  },
  "new-hampshire-post": {
    slug: "new-hampshire-post",
    name: "New Hampshire Post",
    logoFirst: "NEW HAMPSHIRE",
    logoSecond: "POST",
    city: "Manchester",
    state: "New Hampshire",
    stateAbbr: "NH",
    tagline: "New Hampshire's #1 News Source",
  },
  "maine-herald": {
    slug: "maine-herald",
    name: "Maine Herald",
    logoFirst: "MAINE",
    logoSecond: "HERALD",
    city: "Portland",
    state: "Maine",
    stateAbbr: "ME",
    tagline: "Maine's #1 News Source",
  },
  "montana-dispatch": {
    slug: "montana-dispatch",
    name: "Montana Dispatch",
    logoFirst: "MONTANA",
    logoSecond: "DISPATCH",
    city: "Billings",
    state: "Montana",
    stateAbbr: "MT",
    tagline: "Montana's #1 News Source",
  },
  "delaware-times": {
    slug: "delaware-times",
    name: "Delaware Times",
    logoFirst: "DELAWARE",
    logoSecond: "TIMES",
    city: "Wilmington",
    state: "Delaware",
    stateAbbr: "DE",
    tagline: "Delaware's #1 News Source",
  },
  "south-dakota-record": {
    slug: "south-dakota-record",
    name: "South Dakota Record",
    logoFirst: "SOUTH DAKOTA",
    logoSecond: "RECORD",
    city: "Sioux Falls",
    state: "South Dakota",
    stateAbbr: "SD",
    tagline: "South Dakota's #1 News Source",
  },
  "north-dakota-tribune": {
    slug: "north-dakota-tribune",
    name: "North Dakota Tribune",
    logoFirst: "NORTH DAKOTA",
    logoSecond: "TRIBUNE",
    city: "Fargo",
    state: "North Dakota",
    stateAbbr: "ND",
    tagline: "North Dakota's #1 News Source",
  },
  "rhode-island-sun": {
    slug: "rhode-island-sun",
    name: "Rhode Island Sun",
    logoFirst: "RHODE ISLAND",
    logoSecond: "SUN",
    city: "Providence",
    state: "Rhode Island",
    stateAbbr: "RI",
    tagline: "Rhode Island's #1 News Source",
  },
  "vermont-gazette": {
    slug: "vermont-gazette",
    name: "Vermont Gazette",
    logoFirst: "VERMONT",
    logoSecond: "GAZETTE",
    city: "Burlington",
    state: "Vermont",
    stateAbbr: "VT",
    tagline: "Vermont's #1 News Source",
  },
  "wyoming-express": {
    slug: "wyoming-express",
    name: "Wyoming Express",
    logoFirst: "WYOMING",
    logoSecond: "EXPRESS",
    city: "Cheyenne",
    state: "Wyoming",
    stateAbbr: "WY",
    tagline: "Wyoming's #1 News Source",
  },
  "new-jersey-herald": {
    slug: "new-jersey-herald",
    name: "New Jersey Herald",
    logoFirst: "NEW JERSEY",
    logoSecond: "HERALD",
    city: "Newark",
    state: "New Jersey",
    stateAbbr: "NJ",
    tagline: "New Jersey's #1 News Source",
  },
};

export function getActiveSite(): SiteConfig {
  const site = sites[ACTIVE_SITE];
  if (!site) {
    throw new Error(`Site "${ACTIVE_SITE}" not found in sites config.`);
  }
  return site;
}
