import { SiteConfig } from "./site-config";

/**
 * Active site fallback — used when domain detection fails (localhost, etc.)
 * Can be overridden with NEXT_PUBLIC_ACTIVE_SITE env var.
 */
export const ACTIVE_SITE = process.env.NEXT_PUBLIC_ACTIVE_SITE || "alabama-express";

export const sites: Record<string, SiteConfig> = {
  "alabama-express": {
    slug: "alabama-express",
    domain: "alabama-express.com",
    name: "Alabama Express",
    logoFirst: "ALABAMA",
    logoSecond: "EXPRESS",
    city: "Birmingham",
    state: "Alabama",
    stateAbbr: "AL",
    tagline: "Alabama's #1 News Source",
    accent: "#A6192E",
    accentDark: "#811323",
  },
  "alaska-express": {
    slug: "alaska-express",
    domain: "alaskaexpres.com",
    name: "Alaska Express",
    logoFirst: "ALASKA",
    logoSecond: "EXPRESS",
    city: "Anchorage",
    state: "Alaska",
    stateAbbr: "AK",
    tagline: "Alaska's #1 News Source",
    accent: "#0A3161",
    accentDark: "#07264B",
  },
  "arizona-express": {
    slug: "arizona-express",
    domain: "arizona-express.com",
    name: "Arizona Express",
    logoFirst: "ARIZONA",
    logoSecond: "EXPRESS",
    city: "Phoenix",
    state: "Arizona",
    stateAbbr: "AZ",
    tagline: "Arizona's #1 News Source",
    accent: "#B5461E",
    accentDark: "#8D3617",
  },
  "arkansas-express": {
    slug: "arkansas-express",
    domain: "arkansas-express.com",
    name: "Arkansas Express",
    logoFirst: "ARKANSAS",
    logoSecond: "EXPRESS",
    city: "Little Rock",
    state: "Arkansas",
    stateAbbr: "AR",
    tagline: "Arkansas' #1 News Source",
    accent: "#9D2235",
    accentDark: "#7A1A29",
  },
  "california-express": {
    slug: "california-express",
    domain: "californiaexpres.com",
    name: "California Express",
    logoFirst: "CALIFORNIA",
    logoSecond: "EXPRESS",
    city: "Los Angeles",
    state: "California",
    stateAbbr: "CA",
    tagline: "California's #1 News Source",
    accent: "#A63A2A",
    accentDark: "#812D20",
  },
  "colorado-express": {
    slug: "colorado-express",
    domain: "coloradoexpres.com",
    name: "Colorado Express",
    logoFirst: "COLORADO",
    logoSecond: "EXPRESS",
    city: "Denver",
    state: "Colorado",
    stateAbbr: "CO",
    tagline: "Colorado's #1 News Source",
    accent: "#1E4B8F",
    accentDark: "#173A6F",
  },
  "connecticut-express": {
    slug: "connecticut-express",
    domain: "connecticut-express.com",
    name: "Connecticut Express",
    logoFirst: "CONNECTICUT",
    logoSecond: "EXPRESS",
    city: "Hartford",
    state: "Connecticut",
    stateAbbr: "CT",
    tagline: "Connecticut's #1 News Source",
    accent: "#003B5C",
    accentDark: "#002E47",
  },
  "delaware-express": {
    slug: "delaware-express",
    domain: "delaware-express.com",
    name: "Delaware Express",
    logoFirst: "DELAWARE",
    logoSecond: "EXPRESS",
    city: "Wilmington",
    state: "Delaware",
    stateAbbr: "DE",
    tagline: "Delaware's #1 News Source",
    accent: "#00539B",
    accentDark: "#004078",
  },
  "florida-express": {
    slug: "florida-express",
    domain: "florida-expres.com",
    name: "Florida Express",
    logoFirst: "FLORIDA",
    logoSecond: "EXPRESS",
    city: "Miami",
    state: "Florida",
    stateAbbr: "FL",
    tagline: "Florida's #1 News Source",
    accent: "#C74A26",
    accentDark: "#9B391D",
  },
  "georgia-express": {
    slug: "georgia-express",
    domain: "georgia-express.com",
    name: "Georgia Express",
    logoFirst: "GEORGIA",
    logoSecond: "EXPRESS",
    city: "Atlanta",
    state: "Georgia",
    stateAbbr: "GA",
    tagline: "Georgia's #1 News Source",
    accent: "#7B2D26",
    accentDark: "#5F231D",
  },
  "hawaii-express": {
    slug: "hawaii-express",
    domain: "hawaiiexpres.com",
    name: "Hawaii Express",
    logoFirst: "HAWAII",
    logoSecond: "EXPRESS",
    city: "Honolulu",
    state: "Hawaii",
    stateAbbr: "HI",
    tagline: "Hawaii's #1 News Source",
    accent: "#00857D",
    accentDark: "#006761",
  },
  "idaho-express": {
    slug: "idaho-express",
    domain: "idaho-express.com",
    name: "Idaho Express",
    logoFirst: "IDAHO",
    logoSecond: "EXPRESS",
    city: "Boise",
    state: "Idaho",
    stateAbbr: "ID",
    tagline: "Idaho's #1 News Source",
    accent: "#2E5339",
    accentDark: "#23402C",
  },
  "illinois-express": {
    slug: "illinois-express",
    domain: "illinoiseexpres.com",
    name: "Illinois Express",
    logoFirst: "ILLINOIS",
    logoSecond: "EXPRESS",
    city: "Chicago",
    state: "Illinois",
    stateAbbr: "IL",
    tagline: "Illinois' #1 News Source",
    accent: "#13294B",
    accentDark: "#0E1F3A",
  },
  "indiana-express": {
    slug: "indiana-express",
    domain: "indianaexpres.com",
    name: "Indiana Express",
    logoFirst: "INDIANA",
    logoSecond: "EXPRESS",
    city: "Indianapolis",
    state: "Indiana",
    stateAbbr: "IN",
    tagline: "Indiana's #1 News Source",
    accent: "#0C2340",
    accentDark: "#091B31",
  },
  "iowa-express": {
    slug: "iowa-express",
    domain: "iowa-express.com",
    name: "Iowa Express",
    logoFirst: "IOWA",
    logoSecond: "EXPRESS",
    city: "Des Moines",
    state: "Iowa",
    stateAbbr: "IA",
    tagline: "Iowa's #1 News Source",
    accent: "#8C6D31",
    accentDark: "#6D5526",
  },
  "kansas-express": {
    slug: "kansas-express",
    domain: "kansas-express.com",
    name: "Kansas Express",
    logoFirst: "KANSAS",
    logoSecond: "EXPRESS",
    city: "Wichita",
    state: "Kansas",
    stateAbbr: "KS",
    tagline: "Kansas' #1 News Source",
    accent: "#0051BA",
    accentDark: "#003F91",
  },
  "kentucky-express": {
    slug: "kentucky-express",
    domain: "kentucky-express.com",
    name: "Kentucky Express",
    logoFirst: "KENTUCKY",
    logoSecond: "EXPRESS",
    city: "Louisville",
    state: "Kentucky",
    stateAbbr: "KY",
    tagline: "Kentucky's #1 News Source",
    accent: "#4B3F72",
    accentDark: "#3A3158",
  },
  "louisiana-express": {
    slug: "louisiana-express",
    domain: "louisiana-express.com",
    name: "Louisiana Express",
    logoFirst: "LOUISIANA",
    logoSecond: "EXPRESS",
    city: "New Orleans",
    state: "Louisiana",
    stateAbbr: "LA",
    tagline: "Louisiana's #1 News Source",
    accent: "#4A1D6E",
    accentDark: "#391655",
  },
  "maine-express": {
    slug: "maine-express",
    domain: "maineeexpres.com",
    name: "Maine Express",
    logoFirst: "MAINE",
    logoSecond: "EXPRESS",
    city: "Portland",
    state: "Maine",
    stateAbbr: "ME",
    tagline: "Maine's #1 News Source",
    accent: "#14584C",
    accentDark: "#0F443B",
  },
  "maryland-express": {
    slug: "maryland-express",
    domain: "maryland-express.com",
    name: "Maryland Express",
    logoFirst: "MARYLAND",
    logoSecond: "EXPRESS",
    city: "Baltimore",
    state: "Maryland",
    stateAbbr: "MD",
    tagline: "Maryland's #1 News Source",
    accent: "#B06A00",
    accentDark: "#895200",
  },
  "massachusetts-express": {
    slug: "massachusetts-express",
    domain: "massachusettsexpress.com",
    name: "Massachusetts Express",
    logoFirst: "MASSACHUSETTS",
    logoSecond: "EXPRESS",
    city: "Boston",
    state: "Massachusetts",
    stateAbbr: "MA",
    tagline: "Massachusetts' #1 News Source",
    accent: "#12395B",
    accentDark: "#0E2C46",
  },
  "michigan-express": {
    slug: "michigan-express",
    domain: "michigan-express.com",
    name: "Michigan Express",
    logoFirst: "MICHIGAN",
    logoSecond: "EXPRESS",
    city: "Detroit",
    state: "Michigan",
    stateAbbr: "MI",
    tagline: "Michigan's #1 News Source",
    accent: "#00274C",
    accentDark: "#001E3B",
  },
  "minnesota-express": {
    slug: "minnesota-express",
    domain: "minnesota-express.com",
    name: "Minnesota Express",
    logoFirst: "MINNESOTA",
    logoSecond: "EXPRESS",
    city: "Minneapolis",
    state: "Minnesota",
    stateAbbr: "MN",
    tagline: "Minnesota's #1 News Source",
    accent: "#236192",
    accentDark: "#1B4B71",
  },
  "mississippi-express": {
    slug: "mississippi-express",
    domain: "mississippi-express.com",
    name: "Mississippi Express",
    logoFirst: "MISSISSIPPI",
    logoSecond: "EXPRESS",
    city: "Jackson",
    state: "Mississippi",
    stateAbbr: "MS",
    tagline: "Mississippi's #1 News Source",
    accent: "#8B2942",
    accentDark: "#6C1F33",
  },
  "missouri-express": {
    slug: "missouri-express",
    domain: "missouri-express.com",
    name: "Missouri Express",
    logoFirst: "MISSOURI",
    logoSecond: "EXPRESS",
    city: "Kansas City",
    state: "Missouri",
    stateAbbr: "MO",
    tagline: "Missouri's #1 News Source",
    accent: "#B5322E",
    accentDark: "#8D2723",
  },
  "montana-express": {
    slug: "montana-express",
    domain: "montana-express.com",
    name: "Montana Express",
    logoFirst: "MONTANA",
    logoSecond: "EXPRESS",
    city: "Billings",
    state: "Montana",
    stateAbbr: "MT",
    tagline: "Montana's #1 News Source",
    accent: "#1F4E5F",
    accentDark: "#183C4A",
  },
  "nebraska-express": {
    slug: "nebraska-express",
    domain: "nebraska-express.com",
    name: "Nebraska Express",
    logoFirst: "NEBRASKA",
    logoSecond: "EXPRESS",
    city: "Omaha",
    state: "Nebraska",
    stateAbbr: "NE",
    tagline: "Nebraska's #1 News Source",
    accent: "#9B7E46",
    accentDark: "#786236",
  },
  "nevada-express": {
    slug: "nevada-express",
    domain: "nevada-express.com",
    name: "Nevada Express",
    logoFirst: "NEVADA",
    logoSecond: "EXPRESS",
    city: "Las Vegas",
    state: "Nevada",
    stateAbbr: "NV",
    tagline: "Nevada's #1 News Source",
    accent: "#1E4D6B",
    accentDark: "#173C53",
  },
  "new-hampshire-express": {
    slug: "new-hampshire-express",
    domain: "newhampshire-express.com",
    name: "New Hampshire Express",
    logoFirst: "NEW HAMPSHIRE",
    logoSecond: "EXPRESS",
    city: "Manchester",
    state: "New Hampshire",
    stateAbbr: "NH",
    tagline: "New Hampshire's #1 News Source",
    accent: "#2E4A62",
    accentDark: "#23394C",
  },
  "new-jersey-express": {
    slug: "new-jersey-express",
    domain: "newjersey-express.com",
    name: "New Jersey Express",
    logoFirst: "NEW JERSEY",
    logoSecond: "EXPRESS",
    city: "Newark",
    state: "New Jersey",
    stateAbbr: "NJ",
    tagline: "New Jersey's #1 News Source",
    accent: "#A67C2E",
    accentDark: "#816023",
  },
  "new-mexico-express": {
    slug: "new-mexico-express",
    domain: "newmexico-express.com",
    name: "New Mexico Express",
    logoFirst: "NEW MEXICO",
    logoSecond: "EXPRESS",
    city: "Albuquerque",
    state: "New Mexico",
    stateAbbr: "NM",
    tagline: "New Mexico's #1 News Source",
    accent: "#D2492A",
    accentDark: "#A33820",
  },
  "new-york-express": {
    slug: "new-york-express",
    domain: "newyork-express.com",
    name: "New York Express",
    logoFirst: "NEW YORK",
    logoSecond: "EXPRESS",
    city: "New York City",
    state: "New York",
    stateAbbr: "NY",
    tagline: "New York's #1 News Source",
    accent: "#C4530F",
    accentDark: "#98400B",
  },
  "north-carolina-express": {
    slug: "north-carolina-express",
    domain: "northcarolinasexpress.com",
    name: "North Carolina Express",
    logoFirst: "NORTH CAROLINA",
    logoSecond: "EXPRESS",
    city: "Charlotte",
    state: "North Carolina",
    stateAbbr: "NC",
    tagline: "North Carolina's #1 News Source",
    accent: "#1B3F73",
    accentDark: "#153159",
  },
  "north-dakota-express": {
    slug: "north-dakota-express",
    domain: "northdakota-express.com",
    name: "North Dakota Express",
    logoFirst: "NORTH DAKOTA",
    logoSecond: "EXPRESS",
    city: "Fargo",
    state: "North Dakota",
    stateAbbr: "ND",
    tagline: "North Dakota's #1 News Source",
    accent: "#2D5D3A",
    accentDark: "#23482D",
  },
  "ohio-express": {
    slug: "ohio-express",
    domain: "ohioexpres.com",
    name: "Ohio Express",
    logoFirst: "OHIO",
    logoSecond: "EXPRESS",
    city: "Columbus",
    state: "Ohio",
    stateAbbr: "OH",
    tagline: "Ohio's #1 News Source",
    accent: "#BB0000",
    accentDark: "#910000",
  },
  "oklahoma-express": {
    slug: "oklahoma-express",
    domain: "oklahoma-express.com",
    name: "Oklahoma Express",
    logoFirst: "OKLAHOMA",
    logoSecond: "EXPRESS",
    city: "Oklahoma City",
    state: "Oklahoma",
    stateAbbr: "OK",
    tagline: "Oklahoma's #1 News Source",
    accent: "#8C1D40",
    accentDark: "#6D1631",
  },
  "oregon-express": {
    slug: "oregon-express",
    domain: "oregon-express.com",
    name: "Oregon Express",
    logoFirst: "OREGON",
    logoSecond: "EXPRESS",
    city: "Portland",
    state: "Oregon",
    stateAbbr: "OR",
    tagline: "Oregon's #1 News Source",
    accent: "#154734",
    accentDark: "#103728",
  },
  "pennsylvania-express": {
    slug: "pennsylvania-express",
    domain: "pennsylvaniaexpres.com",
    name: "Pennsylvania Express",
    logoFirst: "PENNSYLVANIA",
    logoSecond: "EXPRESS",
    city: "Philadelphia",
    state: "Pennsylvania",
    stateAbbr: "PA",
    tagline: "Pennsylvania's #1 News Source",
    accent: "#862633",
    accentDark: "#681D27",
  },
  "rhode-island-express": {
    slug: "rhode-island-express",
    domain: "rhodeisland-express.com",
    name: "Rhode Island Express",
    logoFirst: "RHODE ISLAND",
    logoSecond: "EXPRESS",
    city: "Providence",
    state: "Rhode Island",
    stateAbbr: "RI",
    tagline: "Rhode Island's #1 News Source",
    accent: "#1D4E89",
    accentDark: "#163C6A",
  },
  "south-carolina-express": {
    slug: "south-carolina-express",
    domain: "southcarolina-express.com",
    name: "South Carolina Express",
    logoFirst: "SOUTH CAROLINA",
    logoSecond: "EXPRESS",
    city: "Charleston",
    state: "South Carolina",
    stateAbbr: "SC",
    tagline: "South Carolina's #1 News Source",
    accent: "#012169",
    accentDark: "#001951",
  },
  "south-dakota-express": {
    slug: "south-dakota-express",
    domain: "southdakota-express.com",
    name: "South Dakota Express",
    logoFirst: "SOUTH DAKOTA",
    logoSecond: "EXPRESS",
    city: "Sioux Falls",
    state: "South Dakota",
    stateAbbr: "SD",
    tagline: "South Dakota's #1 News Source",
    accent: "#3E5C76",
    accentDark: "#30475C",
  },
  "tennessee-express": {
    slug: "tennessee-express",
    domain: "tennesseeexpres.com",
    name: "Tennessee Express",
    logoFirst: "TENNESSEE",
    logoSecond: "EXPRESS",
    city: "Nashville",
    state: "Tennessee",
    stateAbbr: "TN",
    tagline: "Tennessee's #1 News Source",
    accent: "#D96D00",
    accentDark: "#A95500",
  },
  "texas-express": {
    slug: "texas-express",
    domain: "texasexpres.com",
    name: "Texas Express",
    logoFirst: "TEXAS",
    logoSecond: "EXPRESS",
    city: "Austin",
    state: "Texas",
    stateAbbr: "TX",
    tagline: "Texas' #1 News Source",
    accent: "#BF0A30",
    accentDark: "#940725",
  },
  "utah-express": {
    slug: "utah-express",
    domain: "utah-express.com",
    name: "Utah Express",
    logoFirst: "UTAH",
    logoSecond: "EXPRESS",
    city: "Salt Lake City",
    state: "Utah",
    stateAbbr: "UT",
    tagline: "Utah's #1 News Source",
    accent: "#B85C38",
    accentDark: "#8F472B",
  },
  "vermont-express": {
    slug: "vermont-express",
    domain: "vermont-express.com",
    name: "Vermont Express",
    logoFirst: "VERMONT",
    logoSecond: "EXPRESS",
    city: "Burlington",
    state: "Vermont",
    stateAbbr: "VT",
    tagline: "Vermont's #1 News Source",
    accent: "#007A33",
    accentDark: "#005F27",
  },
  "virginia-express": {
    slug: "virginia-express",
    domain: "virginiaexpres.com",
    name: "Virginia Express",
    logoFirst: "VIRGINIA",
    logoSecond: "EXPRESS",
    city: "Richmond",
    state: "Virginia",
    stateAbbr: "VA",
    tagline: "Virginia's #1 News Source",
    accent: "#232D4B",
    accentDark: "#1B233A",
  },
  "washington-express": {
    slug: "washington-express",
    domain: "washingtonexpres.com",
    name: "Washington Express",
    logoFirst: "WASHINGTON",
    logoSecond: "EXPRESS",
    city: "Seattle",
    state: "Washington",
    stateAbbr: "WA",
    tagline: "Washington's #1 News Source",
    accent: "#046A38",
    accentDark: "#03522B",
  },
  "west-virginia-express": {
    slug: "west-virginia-express",
    domain: "westvirginia-express.com",
    name: "West Virginia Express",
    logoFirst: "WEST VIRGINIA",
    logoSecond: "EXPRESS",
    city: "Charleston",
    state: "West Virginia",
    stateAbbr: "WV",
    tagline: "West Virginia's #1 News Source",
    accent: "#002855",
    accentDark: "#001F42",
  },
  "wisconsin-express": {
    slug: "wisconsin-express",
    domain: "wisconsin-express.com",
    name: "Wisconsin Express",
    logoFirst: "WISCONSIN",
    logoSecond: "EXPRESS",
    city: "Milwaukee",
    state: "Wisconsin",
    stateAbbr: "WI",
    tagline: "Wisconsin's #1 News Source",
    accent: "#C5050C",
    accentDark: "#990309",
  },
  "wyoming-express": {
    slug: "wyoming-express",
    domain: "wyoming-express.com",
    name: "Wyoming Express",
    logoFirst: "WYOMING",
    logoSecond: "EXPRESS",
    city: "Cheyenne",
    state: "Wyoming",
    stateAbbr: "WY",
    tagline: "Wyoming's #1 News Source",
    accent: "#7C4D3A",
    accentDark: "#603C2D",
  },
};

/** Lookup site config by domain name */
export function getSiteByDomain(domain: string): SiteConfig | undefined {
  // Clean up domain - remove www., port, trailing dots
  const clean = domain.replace(/^www\./, "").replace(/:\d+$/, "").replace(/\.$/, "").toLowerCase();

  // Exact match first
  const exact = Object.values(sites).find((s) => s.domain.toLowerCase() === clean);
  if (exact) return exact;

  // Partial match (domain contains site domain or vice versa)
  return Object.values(sites).find((s) => clean.includes(s.domain.toLowerCase()) || s.domain.toLowerCase().includes(clean));
}

export function getActiveSite(): SiteConfig {
  const site = sites[ACTIVE_SITE];
  if (!site) {
    throw new Error(`Site "${ACTIVE_SITE}" not found in sites config.`);
  }
  return site;
}
