/**
 * Per-state RSS feeds that actually carry article text.
 *
 * Generated by scripts/find-feeds.mjs, which probes candidate domains and
 * measures how many characters of article body each feed's items contain. Only
 * feeds averaging 500+ characters are here: below that the model would be
 * filling in rather than reporting, which is how this network came to publish
 * invented quotes attributed to real organisations.
 *
 * This replaces Google News RSS. Google News gives a headline, one sentence,
 * and a link wrapped in an opaque identifier that can no longer be resolved to
 * the publisher's URL — so there was no way to reach the article, and no
 * honest way to write one.
 *
 * Regenerate with:  node scripts/find-feeds.mjs --all > scripts/feeds-found.json
 */

export interface StateFeed {
  url: string;
  publisher: string;
  /** Median characters of article text per item, as measured at discovery. */
  medianChars: number;
}

export const STATE_FEEDS: Record<string, StateFeed[]> = {
  "Alabama": [
    { url: "https://alabamareflector.com/feed/", publisher: "alabamareflector.com", medianChars: 5534 },
    { url: "https://wbrc.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "wbrc.com", medianChars: 1563 },
    { url: "https://wsfa.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "wsfa.com", medianChars: 1317 },
    { url: "https://waff.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "waff.com", medianChars: 1245 },
  ],
  "Alaska": [
    { url: "https://alaskabeacon.com/feed/", publisher: "alaskabeacon.com", medianChars: 5534 },
    { url: "https://adn.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "adn.com", medianChars: 5261 },
    { url: "https://ktoo.org/feed/", publisher: "ktoo.org", medianChars: 1754 },
    { url: "https://webcenter11.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "webcenter11.com", medianChars: 1428 },
  ],
  "Arizona": [
    { url: "https://azmirror.com/feed/", publisher: "azmirror.com", medianChars: 5534 },
    { url: "https://kold.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "kold.com", medianChars: 1870 },
  ],
  "Arkansas": [
    { url: "https://arkansasadvocate.com/feed/", publisher: "arkansasadvocate.com", medianChars: 3874 },
    { url: "https://kait8.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "kait8.com", medianChars: 915 },
  ],
  "California": [
    { url: "https://calmatters.org/feed/", publisher: "calmatters.org", medianChars: 6344 },
    { url: "https://voiceofsandiego.org/feed/", publisher: "voiceofsandiego.org", medianChars: 5577 },
  ],
  "Colorado": [
    { url: "https://coloradonewsline.com/feed/", publisher: "coloradonewsline.com", medianChars: 5137 },
    { url: "https://denverite.com/feed/", publisher: "denverite.com", medianChars: 3933 },
    { url: "https://cpr.org/feed/", publisher: "cpr.org", medianChars: 2884 },
    { url: "https://kktv.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "kktv.com", medianChars: 959 },
  ],
  "Connecticut": [
    { url: "https://ctmirror.org/feed/", publisher: "ctmirror.org", medianChars: 4766 },
    { url: "https://wfsb.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "wfsb.com", medianChars: 1824 },
  ],
  "Delaware": [
    { url: "https://spotlightdelaware.org/feed/", publisher: "spotlightdelaware.org", medianChars: 6638 },
  ],
  "Florida": [
    { url: "https://floridaphoenix.com/feed/", publisher: "floridaphoenix.com", medianChars: 5320 },
    { url: "https://wctv.tv/arc/outboundfeeds/rss/?outputType=xml", publisher: "wctv.tv", medianChars: 1826 },
    { url: "https://wjhg.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "wjhg.com", medianChars: 1487 },
  ],
  "Georgia": [
    { url: "https://georgiarecorder.com/feed/", publisher: "georgiarecorder.com", medianChars: 5166 },
    { url: "https://wtoc.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "wtoc.com", medianChars: 1435 },
    { url: "https://wrdw.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "wrdw.com", medianChars: 1242 },
    { url: "https://walb.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "walb.com", medianChars: 1129 },
  ],
  "Hawaii": [
    { url: "https://hawaiinewsnow.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "hawaiinewsnow.com", medianChars: 1870 },
  ],
  "Idaho": [
    { url: "https://idahocapitalsun.com/feed/", publisher: "idahocapitalsun.com", medianChars: 6209 },
    { url: "https://kmvt.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "kmvt.com", medianChars: 982 },
  ],
  "Illinois": [
    { url: "https://wbez.org/rss/", publisher: "wbez.org", medianChars: 13436 },
    { url: "https://injusticewatch.org/feed/", publisher: "injusticewatch.org", medianChars: 8240 },
    { url: "https://chicago.suntimes.com/feed/", publisher: "chicago.suntimes.com", medianChars: 1957 },
    { url: "https://wifr.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "wifr.com", medianChars: 1826 },
  ],
  "Indiana": [
    { url: "https://indianacapitalchronicle.com/feed/", publisher: "indianacapitalchronicle.com", medianChars: 4974 },
    { url: "https://mirrorindy.org/feed/", publisher: "mirrorindy.org", medianChars: 3973 },
    { url: "https://wndu.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "wndu.com", medianChars: 1853 },
  ],
  "Iowa": [
    { url: "https://iowacapitaldispatch.com/feed/", publisher: "iowacapitaldispatch.com", medianChars: 4900 },
    { url: "https://kwqc.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "kwqc.com", medianChars: 1435 },
    { url: "https://kcrg.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "kcrg.com", medianChars: 1327 },
  ],
  "Kansas": [
    { url: "https://kansasreflector.com/feed/", publisher: "kansasreflector.com", medianChars: 6013 },
    { url: "https://kwch.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "kwch.com", medianChars: 1435 },
  ],
  "Kentucky": [
    { url: "https://wfpl.org/feed/", publisher: "wfpl.org", medianChars: 4946 },
    { url: "https://kentuckylantern.com/feed/", publisher: "kentuckylantern.com", medianChars: 4649 },
    { url: "https://wkyt.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "wkyt.com", medianChars: 1870 },
    { url: "https://wave3.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "wave3.com", medianChars: 1845 },
  ],
  "Louisiana": [
    { url: "https://lailluminator.com/feed/", publisher: "lailluminator.com", medianChars: 4185 },
    { url: "https://kplctv.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "kplctv.com", medianChars: 1870 },
    { url: "https://wafb.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "wafb.com", medianChars: 1435 },
    { url: "https://ksla.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "ksla.com", medianChars: 1435 },
  ],
  "Maine": [
    { url: "https://mainemorningstar.com/feed/", publisher: "mainemorningstar.com", medianChars: 4987 },
    { url: "https://bangordailynews.com/feed/", publisher: "bangordailynews.com", medianChars: 3935 },
    { url: "https://wabi.tv/arc/outboundfeeds/rss/?outputType=xml", publisher: "wabi.tv", medianChars: 1982 },
  ],
  "Maryland": [
    { url: "https://marylandmatters.org/feed/", publisher: "marylandmatters.org", medianChars: 5382 },
    { url: "https://wmdt.com/feed/", publisher: "wmdt.com", medianChars: 1232 },
  ],
  "Massachusetts": [
    { url: "https://commonwealthbeacon.org/feed/", publisher: "commonwealthbeacon.org", medianChars: 6942 },
    { url: "https://bostonglobe.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "bostonglobe.com", medianChars: 5319 },
  ],
  "Michigan": [
    { url: "https://michiganadvance.com/feed/", publisher: "michiganadvance.com", medianChars: 6486 },
    { url: "https://bridgemi.com/feed/", publisher: "bridgemi.com", medianChars: 5007 },
    { url: "https://michiganpublic.org/index.rss", publisher: "michiganpublic.org", medianChars: 2537 },
    { url: "https://wilx.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "wilx.com", medianChars: 1982 },
  ],
  "Minnesota": [
    { url: "https://sahanjournal.com/feed/", publisher: "sahanjournal.com", medianChars: 6139 },
    { url: "https://minnesotareformer.com/feed/", publisher: "minnesotareformer.com", medianChars: 4029 },
    { url: "https://kttc.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "kttc.com", medianChars: 1428 },
  ],
  "Mississippi": [
    { url: "https://mississippitoday.org/feed/", publisher: "mississippitoday.org", medianChars: 4496 },
    { url: "https://wlbt.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "wlbt.com", medianChars: 1870 },
    { url: "https://wdam.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "wdam.com", medianChars: 936 },
  ],
  "Missouri": [
    { url: "https://missouriindependent.com/feed/", publisher: "missouriindependent.com", medianChars: 4653 },
    { url: "https://ky3.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "ky3.com", medianChars: 1870 },
    { url: "https://kfvs12.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "kfvs12.com", medianChars: 852 },
  ],
  "Montana": [
    { url: "https://dailymontanan.com/feed/", publisher: "dailymontanan.com", medianChars: 3749 },
    { url: "https://montanafreepress.org/feed/", publisher: "montanafreepress.org", medianChars: 3717 },
  ],
  "Nebraska": [
    { url: "https://flatwaterfreepress.org/feed/", publisher: "flatwaterfreepress.org", medianChars: 4138 },
    { url: "https://nebraskaexaminer.com/feed/", publisher: "nebraskaexaminer.com", medianChars: 3724 },
    { url: "https://1011now.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "1011now.com", medianChars: 1737 },
  ],
  "Nevada": [
    { url: "https://nevadacurrent.com/feed/", publisher: "nevadacurrent.com", medianChars: 5855 },
    { url: "https://thenevadaindependent.com/feed/", publisher: "thenevadaindependent.com", medianChars: 5439 },
    { url: "https://kolotv.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "kolotv.com", medianChars: 959 },
  ],
  "New Hampshire": [
    { url: "https://newhampshirebulletin.com/feed/", publisher: "newhampshirebulletin.com", medianChars: 5621 },
  ],
  "New Jersey": [
    { url: "https://newjerseymonitor.com/feed/", publisher: "newjerseymonitor.com", medianChars: 4987 },
  ],
  "New Mexico": [
    { url: "https://searchlightnm.org/feed/", publisher: "searchlightnm.org", medianChars: 4679 },
    { url: "https://sourcenm.com/feed/", publisher: "sourcenm.com", medianChars: 4174 },
  ],
  "New York": [
    { url: "https://nysfocus.com/feed/", publisher: "nysfocus.com", medianChars: 9131 },
    { url: "https://citylimits.org/feed/", publisher: "citylimits.org", medianChars: 5217 },
    { url: "https://thecity.nyc/feed/", publisher: "thecity.nyc", medianChars: 4526 },
    { url: "https://gothamist.com/feed/", publisher: "gothamist.com", medianChars: 513 },
  ],
  "North Carolina": [
    { url: "https://ncnewsline.com/feed/", publisher: "ncnewsline.com", medianChars: 4184 },
    { url: "https://witn.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "witn.com", medianChars: 1466 },
    { url: "https://wect.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "wect.com", medianChars: 1428 },
  ],
  "North Dakota": [
    { url: "https://inforum.com/index.rss", publisher: "inforum.com", medianChars: 4537 },
    { url: "https://northdakotamonitor.com/feed/", publisher: "northdakotamonitor.com", medianChars: 4381 },
    { url: "https://valleynewslive.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "valleynewslive.com", medianChars: 1870 },
    { url: "https://kfyrtv.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "kfyrtv.com", medianChars: 1385 },
  ],
  "Ohio": [
    { url: "https://signalcleveland.org/feed/", publisher: "signalcleveland.org", medianChars: 6805 },
    { url: "https://ohiocapitaljournal.com/feed/", publisher: "ohiocapitaljournal.com", medianChars: 5745 },
  ],
  "Oklahoma": [
    { url: "https://oklahomavoice.com/feed/", publisher: "oklahomavoice.com", medianChars: 4174 },
    { url: "https://kswo.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "kswo.com", medianChars: 978 },
  ],
  "Oregon": [
    { url: "https://oregoncapitalchronicle.com/feed/", publisher: "oregoncapitalchronicle.com", medianChars: 5534 },
    { url: "https://opb.org/arc/outboundfeeds/rss/?outputType=xml", publisher: "opb.org", medianChars: 2938 },
    { url: "https://ktvz.com/feed/", publisher: "ktvz.com", medianChars: 2791 },
  ],
  "Pennsylvania": [
    { url: "https://penncapital-star.com/feed/", publisher: "penncapital-star.com", medianChars: 6268 },
    { url: "https://witf.org/feed/", publisher: "witf.org", medianChars: 1410 },
    { url: "https://inquirer.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "inquirer.com", medianChars: 1241 },
  ],
  "Rhode Island": [
    { url: "https://rhodeislandcurrent.com/feed/", publisher: "rhodeislandcurrent.com", medianChars: 5715 },
  ],
  "South Carolina": [
    { url: "https://scdailygazette.com/feed/", publisher: "scdailygazette.com", medianChars: 5298 },
    { url: "https://wistv.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "wistv.com", medianChars: 1553 },
    { url: "https://live5news.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "live5news.com", medianChars: 645 },
  ],
  "South Dakota": [
    { url: "https://southdakotasearchlight.com/feed/", publisher: "southdakotasearchlight.com", medianChars: 4805 },
    { url: "https://dakotanewsnow.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "dakotanewsnow.com", medianChars: 3013 },
    { url: "https://kotatv.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "kotatv.com", medianChars: 1435 },
  ],
  "Tennessee": [
    { url: "https://tennesseelookout.com/feed/", publisher: "tennesseelookout.com", medianChars: 4184 },
    { url: "https://wpln.org/feed/", publisher: "wpln.org", medianChars: 2678 },
    { url: "https://wvlt.tv/arc/outboundfeeds/rss/?outputType=xml", publisher: "wvlt.tv", medianChars: 1435 },
    { url: "https://wmcactionnews5.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "wmcactionnews5.com", medianChars: 1272 },
  ],
  "Texas": [
    { url: "https://sacurrent.com/feed/", publisher: "sacurrent.com", medianChars: 2663 },
    { url: "https://kbtx.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "kbtx.com", medianChars: 1982 },
    { url: "https://kwtx.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "kwtx.com", medianChars: 1445 },
    { url: "https://kltv.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "kltv.com", medianChars: 778 },
  ],
  "Utah": [
    { url: "https://deseret.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "deseret.com", medianChars: 6320 },
    { url: "https://utahnewsdispatch.com/feed/", publisher: "utahnewsdispatch.com", medianChars: 5512 },
  ],
  "Vermont": [
    { url: "https://vtdigger.org/feed/", publisher: "vtdigger.org", medianChars: 5334 },
    { url: "https://wcax.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "wcax.com", medianChars: 862 },
  ],
  "Virginia": [
    { url: "https://virginiamercury.com/feed/", publisher: "virginiamercury.com", medianChars: 4655 },
    { url: "https://whsv.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "whsv.com", medianChars: 1870 },
    { url: "https://wdbj7.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "wdbj7.com", medianChars: 1870 },
  ],
  "Washington": [
    { url: "https://washingtonstatestandard.com/feed/", publisher: "washingtonstatestandard.com", medianChars: 4579 },
  ],
  "West Virginia": [
    { url: "https://westvirginiawatch.com/feed/", publisher: "westvirginiawatch.com", medianChars: 4184 },
    { url: "https://wdtv.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "wdtv.com", medianChars: 1113 },
    { url: "https://wsaz.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "wsaz.com", medianChars: 1010 },
  ],
  "Wisconsin": [
    { url: "https://wisconsinexaminer.com/feed/", publisher: "wisconsinexaminer.com", medianChars: 4987 },
    { url: "https://wsaw.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "wsaw.com", medianChars: 1807 },
    { url: "https://wbay.com/arc/outboundfeeds/rss/?outputType=xml", publisher: "wbay.com", medianChars: 1751 },
  ],
  "Wyoming": [
    { url: "https://wyofile.com/feed/", publisher: "wyofile.com", medianChars: 5942 },
  ],
};

export function feedsForState(state: string): StateFeed[] {
  return STATE_FEEDS[state] || [];
}
